# Generated by Django 3.2 on 2022-10-27 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment_app', '0002_onlinedoctorappointment_online_appointment_d'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_id', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('valid_id', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_appointment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appointment_app.onlinedoctorappointment')),
                ('payment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
