# Generated by Django 3.2 on 2022-10-27 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('next_metting_date', models.CharField(blank=True, default='N/A', max_length=200, null=True)),
                ('blood_pressure', models.CharField(blank=True, default='N/A', max_length=20, null=True)),
                ('symptoms', models.TextField(blank=True, default='N/A', max_length=300, null=True)),
                ('suggestions', models.TextField(blank=True, default='N/A', max_length=300, null=True)),
                ('symptoms_for', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='appointment_app.doctorappointment')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=200)),
                ('report_details', models.CharField(blank=True, max_length=200, null=True)),
                ('report_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='appointment_app.doctorappointment')),
            ],
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_file_name', models.CharField(max_length=200)),
                ('report_file', models.FileField(upload_to='folder')),
                ('report_date', models.DateField(auto_now_add=True)),
                ('file_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_file', to='appointment_app.doctorappointment')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=100)),
                ('morning_time', models.IntegerField(blank=True, default=0, null=True)),
                ('lunch_time', models.IntegerField(blank=True, default=0, null=True)),
                ('dinner_time', models.IntegerField(blank=True, default=0, null=True)),
                ('comments', models.CharField(blank=True, max_length=150, null=True)),
                ('prescription_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='appointment_app.doctorappointment')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineSymptoms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('online_next_metting_date', models.CharField(blank=True, default='N/A', max_length=200, null=True)),
                ('online_symptoms', models.TextField(blank=True, default='N/A', max_length=300, null=True)),
                ('online_suggestions', models.TextField(blank=True, default='N/A', max_length=300, null=True)),
                ('online_symptoms_for', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_symptoms', to='appointment_app.onlinedoctorappointment')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineReports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('online_report_name', models.CharField(max_length=200)),
                ('online_report_details', models.CharField(blank=True, max_length=200, null=True)),
                ('online_report_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_report', to='appointment_app.onlinedoctorappointment')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineReportFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('online_report_file', models.FileField(upload_to='folder')),
                ('online_report_date', models.DateField(auto_now_add=True)),
                ('online_report_file_name', models.CharField(max_length=200)),
                ('online_file_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_report_file', to='appointment_app.onlinedoctorappointment')),
            ],
        ),
        migrations.CreateModel(
            name='OnlinePrescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('online_medicine_name', models.CharField(max_length=100)),
                ('online_morning_time', models.IntegerField(blank=True, default=0, null=True)),
                ('online_lunch_time', models.IntegerField(blank=True, default=0, null=True)),
                ('online_dinner_time', models.IntegerField(blank=True, default=0, null=True)),
                ('online_comments', models.CharField(blank=True, max_length=150, null=True)),
                ('Online_prescription_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_prescription', to='appointment_app.onlinedoctorappointment')),
            ],
        ),
    ]
