# Generated by Django 3.2 on 2022-10-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorCatagory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_catagoy', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
