# Generated by Django 3.2 on 2022-10-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAppointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_status', models.BooleanField(default=False)),
                ('added_to_appoint', models.BooleanField(default=False)),
                ('report_status', models.BooleanField(default=False)),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('serial_number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineDoctorAppointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('online_appointment_status', models.BooleanField(default=False)),
                ('online_report_status', models.BooleanField(default=False)),
                ('online_appointment_time', models.TimeField(blank=True, null=True)),
                ('online_serial_number', models.IntegerField(default=1)),
            ],
        ),
    ]
