# Generated by Django 3.2 on 2022-10-27 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor_app', '0001_initial'),
        ('appointment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinedoctorappointment',
            name='online_appointment_d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_appoint', to='doctor_app.onlineappointment'),
        ),
    ]
