# Generated by Django 3.2 on 2022-10-27 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment_app', '0002_onlinedoctorappointment_online_appointment_d'),
        ('doctor_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinedoctorappointment',
            name='online_doctor_d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onlinedoctorappointment',
            name='online_patient_d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='appointment_d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appoint_det', to='doctor_app.appointment'),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='doctor_d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_det', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='patient_d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_det', to=settings.AUTH_USER_MODEL),
        ),
    ]
