# Generated by Django 3.2 on 2022-10-27 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField(default=datetime.date.today)),
                ('time_slot', models.CharField(choices=[('Morning(9.00am-1.00pm)', 'Morning(9.00am-1.00pm)'), ('Afternoon(4.00pm-6.30pm)', 'Afternoon(4.00pm-6.00pm)'), ('Evening(7.30pm-8.30pm)', 'Evening(7.30pm-8.30pm)')], default='Morning(9.00am-1.00am)', max_length=50)),
                ('room_number', models.IntegerField(default=0)),
                ('hospital_name', models.CharField(max_length=200)),
                ('number_of_patient', models.IntegerField(default=1)),
                ('active_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DEACTIVE', 'DEACTIVE')], default='ACTIVE', max_length=10)),
                ('cancel_status', models.BooleanField(default=False)),
                ('cancel_message', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('Dr', 'Dr'), ('Prof Dr', 'Prof Dr'), ('Assoc Prof Dr', 'Assoc Prof Dr'), ('Asst Prof Dr', 'Asst Prof Dr')], default='Dr', max_length=30)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('national_ID_number', models.CharField(max_length=50)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('registration_number_BMDC', models.CharField(max_length=50)),
                ('doctor_type', models.CharField(choices=[('Medical', 'Medical'), ('Dental', 'Dental')], default='Medical', max_length=20)),
                ('road', models.CharField(blank=True, max_length=50)),
                ('sector', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('postcode', models.IntegerField(blank=True, default=1230)),
                ('doctor_sort_description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineAppointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('online_appointment_date', models.DateField(default=datetime.date.today)),
                ('online_time_slot', models.CharField(choices=[('Morning(9.00am-1.00pm)', 'Morning(9.00am-1.00pm)'), ('Afternoon(4.00pm-6.30pm)', 'Afternoon(4.00pm-6.00pm)'), ('Evening(7.30pm-8.30pm)', 'Evening(7.30pm-8.30pm)')], default='Morning(9.00am-1.00am)', max_length=50)),
                ('zoom_link', models.URLField(blank=True, max_length=300, null=True)),
                ('online_number_of_patient', models.IntegerField(default=1)),
                ('online_active_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DEACTIVE', 'DEACTIVE')], default='ACTIVE', max_length=10)),
                ('online_cancel_status', models.BooleanField(default=False)),
                ('online_cancel_message', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
    ]
